### Type definitions saved at 2021-01-15T07:06:24.608Z ###

type File implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type Directory implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type Site implements Node @dontInfer {
  buildTime: Date @dateformat
  siteMetadata: SiteSiteMetadata
  port: Int
  host: String
  polyfill: Boolean
  pathPrefix: String
}

type SiteSiteMetadata @derivedTypes {
  title: String
  description: String
  siteUrl: String
  image: String
  menuLinks: [SiteSiteMetadataMenuLinks]
  postsPerFirstPage: Int
  postsPerPage: Int
  basePath: String
}

type SiteSiteMetadataMenuLinks {
  name: String
  slug: String
}

type SitePage implements Node @dontInfer {
  path: String!
  component: String!
  internalComponentName: String!
  componentChunkName: String!
  matchPath: String
}

type MarkdownHeading {
  id: String
  value: String
  depth: Int
}

enum MarkdownHeadingLevels {
  h1
  h2
  h3
  h4
  h5
  h6
}

enum MarkdownExcerptFormats {
  PLAIN
  HTML
  MARKDOWN
}

type MarkdownWordCount {
  paragraphs: Int
  sentences: Int
  words: Int
}

type MarkdownRemark implements Node @childOf(mimeTypes: [], types: ["contentfulPostBodyTextNode", "contentfulPostMetaDescriptionTextNode", "contentfulPageBodyTextNode", "contentfulPageMetaDescriptionTextNode"], many: false) @dontInfer {
  frontmatter: MarkdownRemarkFrontmatter
  excerpt: String
  rawMarkdownBody: String
}

type MarkdownRemarkFrontmatter {
  title: String
}

type contentfulPostBodyTextNode implements Node @childOf(mimeTypes: [], types: ["ContentfulPost"], many: false) @dontInfer {
  body: String
}

type contentfulPageMetaDescriptionTextNode implements Node @childOf(mimeTypes: [], types: ["ContentfulPage"], many: false) @dontInfer {
  metaDescription: String
}

type contentfulPageBodyTextNode implements Node @childOf(mimeTypes: [], types: ["ContentfulPage"], many: false) @dontInfer {
  body: String
}

type contentfulPostMetaDescriptionTextNode implements Node @childOf(mimeTypes: [], types: ["ContentfulPost"], many: false) @dontInfer {
  metaDescription: String
}

type ContentfulTag implements Node @dontInfer {
  title: String
  slug: String
  post: [ContentfulPost] @link(by: "id", from: "post___NODE")
  spaceId: String
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  sys: ContentfulTagSys
  node_locale: String
}

type ContentfulPost implements Node @dontInfer {
  title: String
  slug: String
  publishDate: Date @dateformat
  heroImage: ContentfulAsset @link(by: "id", from: "heroImage___NODE")
  tags: [ContentfulTag] @link(by: "id", from: "tags___NODE")
  body: contentfulPostBodyTextNode @link(by: "id", from: "body___NODE")
  spaceId: String
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  sys: ContentfulPostSys
  node_locale: String
  metaDescription: contentfulPostMetaDescriptionTextNode @link(by: "id", from: "metaDescription___NODE")
}

type ContentfulAsset implements Node @dontInfer {
  contentful_id: String
  file: ContentfulAssetFile
  title: String
  description: String
  node_locale: String
}

type ContentfulAssetFile {
  url: String
  details: ContentfulAssetFileDetails
  fileName: String
  contentType: String
}

type ContentfulAssetFileDetails {
  size: Int
  image: ContentfulAssetFileDetailsImage
}

type ContentfulAssetFileDetailsImage {
  width: Int
  height: Int
}

type ContentfulPostSys {
  revision: Int
  contentType: ContentfulPostSysContentType
}

type ContentfulPostSysContentType {
  sys: ContentfulPostSysContentTypeSys
}

type ContentfulPostSysContentTypeSys {
  type: String
  linkType: String
  id: String
  contentful_id: String
}

type ContentfulTagSys {
  revision: Int
  contentType: ContentfulTagSysContentType
}

type ContentfulTagSysContentType {
  sys: ContentfulTagSysContentTypeSys
}

type ContentfulTagSysContentTypeSys {
  type: String
  linkType: String
  id: String
  contentful_id: String
}

type ContentfulPage implements Node @dontInfer {
  title: String
  slug: String
  body: contentfulPageBodyTextNode @link(by: "id", from: "body___NODE")
  metaDescription: contentfulPageMetaDescriptionTextNode @link(by: "id", from: "metaDescription___NODE")
  spaceId: String
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  sys: ContentfulPageSys
  node_locale: String
}

type ContentfulPageSys {
  revision: Int
  contentType: ContentfulPageSysContentType
}

type ContentfulPageSysContentType {
  sys: ContentfulPageSysContentTypeSys
}

type ContentfulPageSysContentTypeSys {
  type: String
  linkType: String
  id: String
  contentful_id: String
}

type ContentfulContentType implements Node @dontInfer {
  name: String
  displayField: String
  description: String
}

type contentfulProgramsDescriptionRichTextNode implements Node @derivedTypes @childOf(types: ["ContentfulPrograms"]) @dontInfer {
  content: [contentfulProgramsDescriptionRichTextNodeContent]
  nodeType: String
  description: String
  sys: contentfulProgramsDescriptionRichTextNodeSys
}

type contentfulProgramsDescriptionRichTextNodeContent @derivedTypes {
  content: [contentfulProgramsDescriptionRichTextNodeContentContent]
  nodeType: String
}

type contentfulProgramsDescriptionRichTextNodeContentContent @derivedTypes {
  marks: [contentfulProgramsDescriptionRichTextNodeContentContentMarks]
  value: String
  nodeType: String
}

type contentfulProgramsDescriptionRichTextNodeContentContentMarks {
  type: String
}

type contentfulProgramsDescriptionRichTextNodeSys {
  type: String
}

type ContentfulPrograms implements Node @derivedTypes @dontInfer {
  degreeName: String
  slug: String
  creditHours: Int
  partner: ContentfulPartner @link(by: "id", from: "partner___NODE")
  heroImage: ContentfulAsset @link(by: "id", from: "heroImage___NODE")
  description: contentfulProgramsDescriptionRichTextNode @link(by: "id", from: "description___NODE")
  spaceId: String
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  sys: ContentfulProgramsSys
  node_locale: String
}

type ContentfulPartner implements Node @derivedTypes @dontInfer {
  name: String
  schoolId: Int
  url: String
  logo: ContentfulAsset @link(by: "id", from: "logo___NODE")
  programs: [ContentfulPrograms] @link(by: "id", from: "programs___NODE")
  spaceId: String
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  sys: ContentfulPartnerSys
  node_locale: String
}

type ContentfulPartnerSys @derivedTypes {
  type: String
  revision: Int
  contentType: ContentfulPartnerSysContentType
}

type ContentfulPartnerSysContentType @derivedTypes {
  sys: ContentfulPartnerSysContentTypeSys
}

type ContentfulPartnerSysContentTypeSys {
  type: String
  linkType: String
  id: String
  contentful_id: String
}

type ContentfulProgramsSys @derivedTypes {
  type: String
  revision: Int
  contentType: ContentfulProgramsSysContentType
}

type ContentfulProgramsSysContentType @derivedTypes {
  sys: ContentfulProgramsSysContentTypeSys
}

type ContentfulProgramsSysContentTypeSys {
  type: String
  linkType: String
  id: String
  contentful_id: String
}